---
title: Positive List of 2017 
output: 
  html_document:
    theme: readable
editor_options: 
  chunk_output_type: inline
---

A list of the positive things of 2017 

**Best movies I watched for 1st time:**

- Chicago 
- Baby Driver 


**Best TV series I watched for the 1st time**

- Legion
- Horace and Pete
- Game of Thrones


**Most Intersting concepts I learned:**

- Explorables
- Variational Autoencoders 

**Best Talks:**
- Jonathan Harris: Master Lecture 
- Tadashi Tokedia: Mathematical Toys
- ???


## Other Things

[Nassim Taleb](http://www.fooledbyrandomness.com/), of *black swan* fame, published quite some (unfinished?) chapters of his new book on [medium](https://medium.com/@nntaleb).



### Data Scinece and Machine Learning
There were some very nice and inspiring
 [distill.pub](https://distill.pub/) articles ([1](https://distill.pub/2017/research-debt/), [2](https://distill.pub/2017/momentum/) and especially [3](https://distill.pub/2017/aia/)), but not to many. [Kenneth Stanley](http://www.cs.ucf.edu/~kstanley/) and his group at Uber went ballistic and published a whole series of articles near the end of the year; basically destroying all of my hopes to just chill during my Christmas hollidays. 

### R
First of, [user!2017](https://user2017.brussels/) was a blast. I had lots of fun and the overall climate was productive, inspiring and nice. The folks at [simplystatics](https://simplystatistics.org/) provide an [amazing list](https://simplystatistics.org/2017/12/20/a-non-comprehensive-list-of-awesome-things-other-people-did-in-2017/) about things people did in the R-universe. The [blogdown](https://github.com/rstudio/blogdown) was released by [Yihui Xie](https://yihui.name/) and put many R blogs into my view. [Thomas Lin Pederson](https://www.data-imaginist.com/), the magician behind [ggraph](https://github.com/thomasp85/ggraph) wrote about his packages of 2017, and the problems that came with it. The tidyverse got a [hub](https://www.tidyverse.org/) and with it came a lot of content, such as the [tidyverse styleguide](http://style.tidyverse.org/) and [tidy-evaluation](https://cran.r-project.org/web/packages/rlang/vignettes/tidy-evaluation.html). [Rstudio](https://www.data-imaginist.com/2017/looking-back-on-2017/) also came up with [community page](), which seems to be well thought out. But, I personally did not catch on.
